"""Render shared static components and new learning pages. Python standard library only."""
from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parent.parent
E=html.escape
def load(n):return json.loads((ROOT/'data'/f'{n}.json').read_text())
mods=load('modules');questions=load('questions');cases=load('cases');challenge=load('challenges')
navlinks=[('index.html#aprender','Aprender'),('explorar.html','Explorar'),('laboratorio.html','Laboratorio'),('poder.html','Poder & influencia'),('progreso.html','Mi progreso'),('autor.html','Autor')]
def nav(file):return '<a class="fp-skip" href="#contenido">Saltar al contenido</a><nav class="fp-nav" aria-label="Navegación principal"><a class="fp-brand" href="index.html">Filosofía &amp; Política</a><button class="fp-menu" aria-expanded="false" aria-controls="fp-links">Menú</button><div class="fp-links" id="fp-links">'+''.join(f'<a href="{url}"'+(' aria-current="page"' if url.split('#')[0]==file else '')+f'>{E(name)}</a>' for url,name in navlinks)+'</div></nav>'
footer='<footer class="fp-footer"><p>Filosofía &amp; Política · Proyecto de aprendizaje de Rodrigo Vidal</p><p><a href="retos.html">Reto y pregunta del mes</a> · <a href="presente.html">Teoría ↔ Presente</a> · <a href="https://rozoca.github.io/">Perfil profesional ↗</a></p><p>Aprender no para acumular respuestas, sino para mejorar las preguntas.</p></footer>'
levels='<div class="fp-levels"><span>01 · Reconocer</span><span>02 · Explicar</span><span>03 · Comparar</span><span>04 · Aplicar</span></div>'
def page(file,key,title,lead,body):
 desc=E(lead,quote=True);t=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} · Filosofía &amp; Política</title><meta name="description" content="{desc}"><link rel="stylesheet" href="assets/css/portal.css"><script type="module" src="assets/js/common.js"></script><script type="module" src="assets/js/app.js"></script></head><body class="fp-page" data-page="{key}"><!-- FP:NAV --><main class="fp-wrap" id="contenido"><p class="fp-kicker">Filosofía &amp; Política / Aprendizaje activo</p><h1>{E(title)}</h1><p class="fp-lead">{E(lead)}</p>{body}<noscript><p class="fp-note">Esta sección interactiva requiere JavaScript. Puedes seguir leyendo todos los <a href="index.html#aprender">módulos históricos</a>.</p></noscript></main><!-- FP:FOOTER --></body></html>''';(ROOT/file).write_text(t)
page('explorar.html','explore','Una pregunta, varias perspectivas','Cruza épocas y autores a través de diez grandes problemas. Elige un tema, estudia sus diferencias y llévalas al Laboratorio.','''<section class="fp-section"><div class="fp-filters"><label>Gran problema<select id="topic"></select></label><label>Buscar autor o concepto<input id="search" type="search" placeholder="Por ejemplo: libertad"></label></div><p id="explore-count" role="status"></p><div id="explore-results" class="fp-grid"></div></section>''')
labbody=levels+'''<section class="fp-section" aria-labelledby="test-title"><h2 id="test-title">Ponte a prueba</h2><p>Test rápido: hasta 5 preguntas, 3–5 minutos, con explicación inmediata. Examen: hasta 10 preguntas y feedback al terminar. Para un examen acumulativo, deja todos los filtros abiertos.</p><form id="quiz-settings"><div class="fp-filters"><label>Formato<select id="mode"><option value="quick">Test rápido</option><option value="exam">Modo examen</option></select></label><label>Autor<select id="author"></select></label><label>Fase<select id="phase"><option value="">Todas las fases publicadas</option><option value="1">I · Antigüedad y Edad Media</option><option value="2">II · Modernidad</option><option value="3">III · Siglo XIX</option><option value="4">IV · Economía política</option></select></label><label>Temática<select id="topic"></select></label><label>Dificultad<select id="difficulty"><option value="">Todas</option><option>Básico</option><option>Intermedio</option><option>Avanzado</option></select></label></div><p id="pool-count" role="status">Cargando preguntas…</p><p id="filter-context"></p><button id="start" type="submit" disabled>Comenzar</button></form><div id="quiz-stage" hidden></div><section id="quiz-results" hidden></section></section><section class="fp-section"><h2>Pensar más allá de la respuesta correcta</h2><div class="fp-grid">'''
for kind,title,text in [('caso','Casos prácticos','8 situaciones para comparar diagnósticos y justificar decisiones.'),('dilema','Dilemas','Dos tensiones abiertas: vigilancia y expresión. Examina costes y límites.'),('socratico','Reto socrático','Desmonta definiciones, busca contraejemplos y revela supuestos.'),('transferencia','Transferencia','Aplica una idea fuera de su contexto y reconoce dónde deja de funcionar.')]:labbody+=f'<article class="fp-card"><h3>{title}</h3><p>{text}</p><a href="casos.html?tipo={kind}">Entrenar →</a></article>'
labbody+='''</div><div class="fp-actions"><a class="fp-button fp-secondary" href="retos.html">Reto del mes</a><a class="fp-button fp-secondary" href="presente.html">Teoría ↔ Presente</a><a class="fp-button fp-secondary" href="progreso.html">Revisar mi progreso</a></div></section>'''
page('laboratorio.html','lab','Laboratorio de pensamiento','Estudia, contrasta, equivócate con una explicación y vuelve a intentarlo. Aquí el error señala qué merece una segunda lectura.',labbody)
page('casos.html','cases','Ideas en situaciones reales','Casos hipotéticos para entrenar criterio. Escribe primero, compara después y revisa tu argumento: puede haber varias respuestas defendibles.','''<section class="fp-section"><label>Tipo de actividad<select id="kind"><option value="">Todas las actividades</option><option value="caso">Casos prácticos</option><option value="dilema">Dilemas</option><option value="socratico">Reto socrático</option><option value="transferencia">Transferencia</option></select></label><p id="case-count" role="status"></p><div id="activities" class="fp-grid"></div></section>''')
page('retos.html','monthly','Del concepto a la semana','Una práctica pequeña, observada con atención, puede enseñar más que una colección de definiciones.','''<p id="edition" class="fp-kicker"></p><section class="fp-section"><h2>Pregunta del mes</h2><p id="month-question" class="fp-lead"></p><p>No busques una respuesta inmediata. Anota un ejemplo y un contraejemplo; vuelve al final de la semana.</p></section><section id="monthly-activity" class="fp-section"></section>''')
page('presente.html','present','Teoría ↔ Presente','Hechos fechados, interpretaciones explícitas y preguntas abiertas. Hitos contemporáneos para pensar, sin presentarlos como noticias de última hora.','''<section class="fp-section"><div id="present-entries" class="fp-grid"></div><div class="fp-actions"><a class="fp-button fp-secondary" href="casos.html">Practicar el análisis en un caso</a></div></section>''')
page('progreso.html','progress','Mi progreso','No se trata de acumular puntos. Se trata de reconocer lo que puedes explicar y descubrir lo que aún merece estudio.','''<div id="progress-data"></div><section class="fp-section"><h2>Tus datos, en este navegador</h2><p>Sin cuentas ni envío de respuestas a un servidor. Otro dispositivo o navegador tendrá un historial diferente. Borrar los datos del navegador elimina el progreso; exporta una copia si quieres conservarlo.</p><div class="fp-actions"><button id="export">Exportar copia</button><button id="reset" class="fp-secondary">Restablecer progreso</button></div><label>Restaurar una copia JSON<input id="import" type="file" accept="application/json,.json"></label><p id="data-status" class="fp-status" role="status"></p></section>''')
power='''<section class="fp-section"><h2>Antes de juzgar, distingue</h2><div class="fp-grid"><article class="fp-card"><h3>Poder, autoridad y legitimidad</h3><p>Poder es capacidad de afectar acciones o posibilidades. Autoridad es un derecho reconocido a dirigir dentro de un ámbito. Legitimidad pregunta por la justificación de ese reconocimiento: eficacia, obediencia y justicia no son equivalentes.</p><p>Una jefatura tiene poder formal. Una persona de confianza puede tener influencia real sin firma. Ni el cargo garantiza apoyo ni el apoyo justifica todo.</p></article><article class="fp-card"><h3>Persuadir y manipular</h3><p>La persuasión ofrece razones que pueden examinarse. La manipulación puede distorsionar información, ocultar fines o explotar dependencias para restringir una elección autónoma. La frontera exige atender al contexto.</p><p>Pregunta: ¿puedo disentir, conocer alternativas y rechazar sin un coste injustificado?</p></article></div></section><section class="fp-section"><h2>Una pregunta justifica cada modelo</h2><div class="fp-grid">'''
for m in load('power'):power+=f'<article class="fp-card"><p class="fp-kicker">{E(m["author"])}</p><h3>{E(m["question"])}</h3><p>{E(m["idea"])}</p><p><strong>Para observar:</strong> {E(m["practice"])}</p><p class="fp-muted">Lectura de referencia: {E(m["reference"])}</p></article>'
power+='''</div><p class="fp-muted">Fuentes adicionales: <a href="https://web.mit.edu/curhan/www/docs/Articles/15341_Readings/Power/French_%26_Raven_The_Bases_of_Social_Power_ch32_pp607-623.pdf">French y Raven · texto original</a> · <a href="https://doi.org/10.1111/j.1540-4560.1993.tb01191.x">Raven · revisión del modelo</a> · <a href="https://www.influenceatwork.com/principles-of-persuasion-are-not-just-for-business/">Cialdini · persuasión ética</a>.</p></section><section class="fp-section"><h2>Leer una reunión sin inventar intenciones</h2><div class="fp-card"><ol><li>Identifica quién decide formalmente y quién cambia opiniones.</li><li>Observa quién controla información, recursos, agenda o acceso a otras personas.</li><li>Separa reputación y estatus de conocimiento demostrado. Pregunta qué incentivos y dependencias existen.</li><li>Registra silencios y alianzas como observaciones incompletas: callar no prueba acuerdo ni miedo.</li><li>Formula dos explicaciones alternativas y una pregunta respetuosa para contrastarlas.</li></ol><p>Negociar mejora cuando comprendes intereses, alternativas y límites. No utilices estos modelos para explotar vulnerabilidades. El objetivo es ampliar autonomía y capacidad de cooperación.</p><div class="fp-actions"><a class="fp-button" href="retos.html">Practicar durante una semana</a><a class="fp-button fp-secondary" href="casos.html?id=experta">La experta sin cargo</a></div></div></section><section class="fp-section"><h2>Conectar con el itinerario</h2><p><a href="aristoteles-politica.html">Aristóteles: bien común</a> · <a href="maquiavelo.html">Maquiavelo: estabilidad</a> · <a href="hobbes.html">Hobbes: garantía del orden</a> · <a href="nietzsche.html">Nietzsche: creación de valores</a> · <a href="explorar.html?tema=Poder">Explorar todas las lecturas sobre poder</a></p></section>'''
page('poder.html','power','Poder, influencia y relaciones humanas','Comprender por qué obedecemos, quién influye y qué sostiene una dependencia. Observar mejor para decidir con más autonomía.',power)
# Idempotent shared components on all pages, including historical modules.
for p in ROOT.glob('*.html'):
 t=p.read_text();t=re.sub(r'<!-- FP:NAV:START -->.*?<!-- FP:NAV:END -->','<!-- FP:NAV -->',t,flags=re.S);t=re.sub(r'<!-- FP:FOOTER:START -->.*?<!-- FP:FOOTER:END -->','<!-- FP:FOOTER -->',t,flags=re.S)
 t=t.replace('<!-- FP:NAV -->','<!-- FP:NAV:START -->'+nav(p.name)+'<!-- FP:NAV:END -->').replace('<!-- FP:FOOTER -->','<!-- FP:FOOTER:START -->'+footer+'<!-- FP:FOOTER:END -->')
 if 'data-document=' not in t:t=t.replace('<body',f'<body data-document="{p.name}"',1)
 if 'assets/css/legacy-contrast.css' not in t:t=t.replace('</head>','<link rel="stylesheet" href="assets/css/legacy-contrast.css"></head>')
 # Semantic main landmark for historical pages without one.
 if '<main' not in t:
  t=t.replace('<div id="contenido" tabindex="-1"></div>','')
  t=t.replace('<!-- FP:NAV:END -->','<!-- FP:NAV:END --><main id="contenido">')
  t=t.replace('<!-- FP:FOOTER:START -->','</main><!-- FP:FOOTER:START -->',1)
 # basic metadata regenerated as a bounded block
 t=re.sub(r'<!-- FP:META:START -->.*?<!-- FP:META:END -->\n?','',t,flags=re.S)
 title=html.unescape(re.search(r'<title>(.*?)</title>',t,re.S)[1]);desc=re.search(r'<meta name="description" content="([^"]*)"',t)
 description=html.unescape(desc[1]) if desc else f'{title}. Estudia, compara autores y practica pensamiento crítico en el portal de Rodrigo Vidal.'
 url='https://rozoca.github.io/filosofia-politica/'+('' if p.name=='index.html' else p.name)
 meta=f'<meta name="author" content="Rodrigo Vidal"><meta name="theme-color" content="#1e1b16"><link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:title" content="{E(title,quote=True)}"><meta property="og:description" content="{E(description,quote=True)}"><meta property="og:url" content="{url}"><meta property="og:locale" content="es_ES">'
 if not desc:meta+=f'<meta name="description" content="{E(description,quote=True)}">'
 t=t.replace('</head>','<!-- FP:META:START -->'+meta+'<!-- FP:META:END -->\n</head>')
 if 'id="contenido"' not in t:
  if '<main' in t:t=re.sub(r'<main\b','<main id="contenido"',t,count=1)
  else:t=t.replace('<!-- FP:NAV:END -->','<!-- FP:NAV:END --><div id="contenido" tabindex="-1"></div>')
 mod=next((m for m in mods if m['url']==p.name),None)
 if mod:
  if 'data-module=' not in t:t=t.replace('<body>','<body data-module="'+mod['id']+'">')
  block=f'<section class="fp-practice" aria-label="Practica lo aprendido"><p class="fp-kicker">Comprender → Comparar → Aplicar</p><h2>Practica lo aprendido</h2><p>Contrasta tu comprensión de {E(mod["title"])}. Después explica con tus palabras dónde sirve la teoría y dónde encuentra sus límites.</p><div class="fp-actions"><a class="fp-button" href="laboratorio.html?module={mod["id"]}">Test del módulo</a><a class="fp-button fp-secondary" href="casos.html?module={mod["id"]}">Casos y comparación</a><a href="laboratorio.html">Volver al Laboratorio →</a></div></section>'
  if '<!-- FP:PRACTICE:START -->' in t:t=re.sub(r'<!-- FP:PRACTICE:START -->.*?<!-- FP:PRACTICE:END -->','<!-- FP:PRACTICE:START -->'+block+'<!-- FP:PRACTICE:END -->',t,flags=re.S)
  else:t=t.replace('<!-- FP:FOOTER:START -->','<!-- FP:PRACTICE:START -->'+block+'<!-- FP:PRACTICE:END --><!-- FP:FOOTER:START -->')
 # avoid two footers while preserving author links in common footer
 t=re.sub(r'<footer(?! class="fp-footer")[\s\S]*?</footer>','',t)
 p.write_text(t)
# learning entrance on the preserved home page
p=ROOT/'index.html';t=p.read_text();block='''<section class="fp-home"><p class="fp-kicker">Tu siguiente paso</p><h2>Leer es el comienzo. Pensar se entrena.</h2><div class="fp-grid fp-grid-three"><div><h3>01 · Aprender</h3><p>18 módulos y un epílogo. Recorre las ideas en su contexto.</p><a href="#aprender">Seguir el itinerario →</a></div><div><h3>02 · Explorar</h3><p>Una misma pregunta, autores distintos: libertad, justicia, poder.</p><a href="explorar.html">Cruzar perspectivas →</a></div><div><h3>03 · Practicar</h3><p>40 preguntas y 8 casos. Recibe feedback y vuelve sobre tus lagunas.</p><a href="laboratorio.html">Entrar al Laboratorio →</a></div></div><div class="fp-actions"><a href="poder.html">Poder &amp; influencia</a><a href="retos.html">Reto del mes</a><a href="presente.html">Teoría ↔ Presente</a></div></section>'''
if '<!-- FP:HOME:START -->' in t:t=re.sub(r'<!-- FP:HOME:START -->.*?<!-- FP:HOME:END -->','<!-- FP:HOME:START -->'+block+'<!-- FP:HOME:END -->',t,flags=re.S)
else:t=t.replace('<div class="greek-line"></div>','<!-- FP:HOME:START -->'+block+'<!-- FP:HOME:END --><div class="greek-line"></div>',1)
t=t.replace('18 módulos y un epílogo.',f'{sum(m["kind"]=="module" for m in mods)} módulos y un epílogo.').replace('40 preguntas y 8 casos.',f'{len(questions)} preguntas y {sum(c["kind"]=="caso" for c in cases)} casos.')
p.write_text(t)
urls=['https://rozoca.github.io/filosofia-politica/'+('' if p.name=='index.html' else p.name) for p in sorted(ROOT.glob('*.html'))]
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in urls)+'</urlset>')
print(f'Built shared shell and 7 learning pages; {len(urls)} pages in sitemap.')
